name: miss_hit

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: ['*']

jobs:
  set_up:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install -r requirements.txt

  style:
    needs: set_up
    runs-on: ubuntu-latest

    steps:

    - name: MISS_HIT Code style
      run: |
        mh_style

  quality:
    needs: set_up
    runs-on: ubuntu-latest

    steps:

    - name: MISS_HIT Metrics
      run: |
        mh_metric --ci
        
    - name: MISS_HIT Bug finder
      run: |
        mh_lint
