name: system tests with matlab

# Uses the cron schedule for github actions
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
#
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1,15 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  set_up:

    runs-on: ubuntu-20.04

    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1.0.1
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Clone cpp_spm
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2

      - name: Install SPM
        run: |
          git clone https://github.com/spm/spm12.git --depth 1

      - name: Copy Macs toolbox to SPM inputs_folder
        run: cp -rv lib/MACS spm12/toolbox/MACS

      - name: Run commands
        uses: matlab-actions/run-command@v1.0.1
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run system_tests_matlab;

  moae:
    needs: set_up

    runs-on: ubuntu-20.04

    steps:
      - name: Run test_moae
        uses: matlab-actions/run-command@v1.0.1
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run system_tests_moae;

  face_rep:
    needs: set_up

    runs-on: ubuntu-20.04

    steps:
      - name: Run face_rep_resolution
        uses: matlab-actions/run-command@v1.0.1
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run system_tests_facerep;
