name: tests and coverage with matlab

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1.0.1
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Clone cpp_spm
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2

      - name: Install SPM
        run: |
          git clone https://github.com/spm/spm12.git --depth 1

      - name: Install Moxunit and MOcov
        run: |
          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
          git clone https://github.com/MOcov/MOcov.git --depth 1


      - name: Copy Macs toolbox to SPM inputs_folder
        run: cp -rv lib/MACS spm12/toolbox/MACS

      - name: Prepare data
        run: | # download MoAE from OSF (see this for API: https://github.com/CenterForOpenScience/osf.io/issues/8256)
          URL=https://files.de-1.osf.io/v1/resources/3vufp/providers/osfstorage/6239d943938b48080c97b6d4/?zip=
          inputs_folder='demos/MoAE/inputs/'
          mkdir -p $inputs_folder
          curl $URL --output $inputs_folder'MoAEpilot.zip'
          unzip $inputs_folder'MoAEpilot.zip' -d $inputs_folder/MoAEpilot
          mv $inputs_folder/MoAEpilot $inputs_folder/raw
          cd tests
          make data

      - name: Run commands
        uses: matlab-actions/run-command@v1.0.1
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;

      - name: Run tests
        run: |
          cat test_report.log | grep 0
          bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage_file
          path: coverage.xml

      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
